Status lifetime
ph-ash/server pull request #48
Opened 2019-09-27 14:04 UTC by cHeeSaW

show lifetime of the status in modal-dialog

2019-10-01 07:14 UTC, cawolf requested changes

2019-10-01 07:14 UTC, cawolf commented on src/Factory/MonitoringDataDtoFactoryService.php
> +    public function createOutgoingFromIncoming(IncomingMonitoringDataDto $monitoringData): MonitoringDataDto
looks unused to me

2019-10-02 16:04 UTC, cHeeSaW commented on src/Factory/MonitoringDataDtoFactoryService.php
> +    public function createOutgoingFromIncoming(IncomingMonitoringDataDto $monitoringData): MonitoringDataDto
removed

2019-10-04 06:31 UTC, cawolf requested changes
builds are failing right now

2019-10-04 06:31 UTC, cawolf commented on src/Factory/MonitoringDataDtoFactory.php
> +    public function createOutgoingFromIncoming(IncomingMonitoringDataDto $monitoringData): OutgoingMonitoringDataDto;
the interface still contains the deleted function

2019-10-04 12:45 UTC, cawolf approved these changes

2019-10-04 12:46 UTC, merged