Delete monitorings
ph-ash/server pull request #6
Opened 2019-02-28 22:51 UTC by cHeeSaW

2019-03-06 20:16 UTC, cawolf requested changes

2019-03-06 20:16 UTC, cawolf commented on src/Command/PhashBoardClientCommand.php
> +    )
neuer CS

2019-03-06 20:16 UTC, cawolf commented on src/Command/PhashBoardClientCommand.php
> +        //send monitoringdata to the board
irreführender Kommentar (c&p?)

2019-03-06 20:16 UTC, cawolf commented on src/Command/PhashBoardClientCommand.php
> +                $this->consoleLogger->info(self::ZMQ_PREFIX . 'Received {message} on channel {channel}', ['message' => $payload[1], 'channel' => $payload[0]]);
Muss man hier ZMQ-bedingt mit Array-Indizes `0` und `1` arbeiten, oder kann man hier auch was Sprechendes reinbauen?

2019-03-06 20:16 UTC, cawolf commented on src/Controller/Rest/MonitoringController.php
>  use FOS\RestBundle\Controller\FOSRestController;
kannst du bitte mal den neuesten `master` reinziehen? Die Deprecation ist da schon gelöst.

2019-03-06 20:16 UTC, cawolf commented on src/Controller/Rest/MonitoringController.php
> +    {
neuer CS * 3

2019-03-06 20:16 UTC, cawolf commented on src/Controller/Rest/MonitoringController.php
> +     *     allowEmptyValue=false,
bedeutet das im Zusammenspiel mit dem ParamConverter für `MonitoringData`, dass ich für das Löschen eines Monitorings *alle* Daten brauche, und nicht nur die ID?
Warum gibt es keinen Endpunkt a la `DELETE /monitoring/{id}`? Mit `/data` hat das ja nichts zu tun.

2019-03-06 20:16 UTC, cawolf commented on src/Event/DeleteMonitoringDataEvent.php
> +    public function __construct(MonitoringData $monitoringData)
ergibt sich aus der obigen Anmerkung: warum trägt das Event mehr als die ID? Nur die wird für das Löschen gebraucht.

2019-03-06 20:16 UTC, cawolf commented on src/Event/MonitoringDataEvent.php
> +interface MonitoringDataEvent
Wäre mit obiger Anmerkung ggfs. obsolet

2019-03-06 20:16 UTC, cawolf commented on src/EventSubscriber/BoardSubscriber.php
> +     * @throws ZMQClientException
unhandled exceptions

2019-03-06 20:16 UTC, cawolf commented on src/EventSubscriber/BoardSubscriber.php
> +     * @throws ZMQClientException
unhandled exceptions

2019-03-06 20:16 UTC, cawolf commented on src/EventSubscriber/ValidationSubscriber.php
> +            DeleteMonitoringDataEvent::EVENT_DELETE_MONITORING_DATA => ['validateMonitoringData', 0]
Das führt in der jetzigen Implementierung dazu, dass bei DELETE einer richtigen ID, aber eines falschen `path` das DELETE abgelehnt wird - finde ich unintuitiv

2019-03-06 20:16 UTC, cawolf commented on src/Factory/DeleteMonitoringDataEvent.php
> +
keine `strict_types`

2019-03-06 20:16 UTC, cawolf commented on src/Repository/MonitoringData.php
> +    public function findAll(): array;
könnte man noch mit `MonitoringDataDocument[]` hinten

2019-03-06 20:16 UTC, cawolf commented on src/Repository/MonitoringDataRepository.php
> +use App\Dto\MonitoringData as MonitoringDataDto;
unused import

2019-03-06 20:16 UTC, cawolf commented on src/Service/Board/ZMQ/ClientService.php
> +     * @throws ZMQClientException
DocBlock schon im Interface vorhanden

2019-03-06 20:16 UTC, cawolf commented on src/Service/DeleteMonitoringDataDispatcherService.php
> +    private $deleteMonitoringDataEvent;
Generll: bis zur Benutzung geht weder aus dem Typehint im `__construct` noch aus dem Namen direkt hervor, dass es sich hier um eine Factory handelt.

2019-03-06 20:16 UTC, cawolf commented on tests/Unit/Service/Board/MonitoringDataDeletionServiceTest.php
> +
fehlende `strict_types`

2019-03-06 20:16 UTC, cawolf commented on tests/Unit/Service/Board/MonitoringDataPushServiceTest.php
> +use Prophecy\Argument;
unused import

2019-03-06 20:16 UTC, cawolf commented on tests/Unit/Service/Board/ZMQ/PushClientServiceTest.php
> +use App\Service\Board\ZMQ\ClientService;
Sollte dann der Test nicht auch umbenannt werden in `ClientServiceTest`?

2019-03-06 20:16 UTC, cawolf commented on tests/Unit/Service/Board/ZMQ/PushClientServiceTest.php
fehlende `strict_types`

2019-03-06 20:16 UTC, cawolf commented on src/EventSubscriber/ValidationSubscriber.php
> +    public function validateMonitoringData(MonitoringDataEvent $incomingMonitoringDataEvent): void
Parameter wäre im jetzigen Code-Stand falsch benannt, da auch ein `DeleteMonitoringDataEvent` eingehen könnte.

2019-03-06 20:16 UTC, cawolf commented on src/EventSubscriber/ValidationSubscriber.php
> +        if (!$incomingMonitoringDataEvent instanceof Event) {
Die Prüfung ist überflüssig, genauso wie das `$incomingMonitoringDataEvent->stopPropagation()` im `catch`-Block: die Event-Behandlung wird bei einer Exception sowieso abgebrochen.

2019-03-06 21:19 UTC, cHeeSaW commented on src/Command/PhashBoardClientCommand.php
> +                $this->consoleLogger->info(self::ZMQ_PREFIX . 'Received {message} on channel {channel}', ['message' => $payload[1], 'channel' => $payload[0]]);
ich befürchte leider ja. Kann mal beim senden probieren keys mitzuschicken, aber ich glaub das wird ignoriert oder knallt

2019-03-06 21:24 UTC, cHeeSaW commented on src/EventSubscriber/ValidationSubscriber.php
> +    public function validateMonitoringData(MonitoringDataEvent $incomingMonitoringDataEvent): void
MonitoringDataEvent ist ein Interface, daher würde das passen, aber ja, ist vielleicht verwirrend. Ich ziehs raus

2019-03-06 21:28 UTC, cHeeSaW commented on src/Command/PhashBoardClientCommand.php
> +                $this->consoleLogger->info(self::ZMQ_PREFIX . 'Received {message} on channel {channel}', ['message' => $payload[1], 'channel' => $payload[0]]);
wahrscheinlich schon, ich werde mal ausprobieren ob er beim senden der nachrichten keys übernimmt wenn ich sie mit reingebe

2019-03-06 22:23 UTC, cHeeSaW commented on src/Service/DeleteMonitoringDataDispatcherService.php
> +    private $deleteMonitoringDataEvent;
aber aus dem Namespace?

2019-03-07 23:48 UTC, cawolf commented on src/Service/DeleteMonitoringDataDispatcherService.php
> +    private $deleteMonitoringDataEvent;
Das ist, was ich sehe, wenn ich die Datei öffne: https://imgur.com/a/wZPy0n4
Daraus seh ich erstmal gar nix. Wenn ich erst oben aufklappen muss, um die Properties zu verstehen, finde ich das Naming nicht gut. Dann würde ich eher mit Aliases arbeiten, um den jeweiligen Typ des Parameters/der Property erfassen zu können.

2019-03-08 14:57 UTC, cawolf approved these changes

2019-03-09 23:48 UTC, merged